// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestWebApi.Integration.Database.Entities;

public partial class Department
{
    public int DepartmentId { get; set; }

    public int Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<EmployeeDepartment> EmployeeDepartments { get; } = new List<EmployeeDepartment>();
}