// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestWebApi.Integration.Database.Entities;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string Code { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime BirthDate { get; set; }

    public string Sex { get; set; }

    public bool Inactive { get; set; }

    public virtual ICollection<EmployeeDepartment> EmployeeDepartments { get; } = new List<EmployeeDepartment>();

    public virtual ICollection<Physician> Physicians { get; } = new List<Physician>();
}