// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestWebApi.Integration.Database.Entities;

public partial class Physician
{
    public int PhysicianId { get; set; }

    public int EmployeeId { get; set; }

    public string Riziv { get; set; }

    public string Title { get; set; }

    public virtual Employee Employee { get; set; }
}